# Generated by Django 2.2.5 on 2019-09-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20190926_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
